"""
Ultrasonic deterrent controller — drives a 20–40 kHz transducer via pigpio
hardware PWM (GPIO18 / PWM0). Hardware PWM is generated by the SoC's PWM
peripheral, so tones stay clean and jitter-free even at ultrasonic frequencies
(software PWM cannot do this — it relies on a CPU thread toggling the pin).

A passive/audible buzzer resonates ~2–4 kHz and will be silent up here; use a
true ultrasonic transducer (e.g. a 40 kHz piezo) on the buzzer pin.
"""

import random
import time

import config


class Buzzer:
    def __init__(self, pi, pin: int):
        """
        pi  : a connected pigpio.pi() instance (shared with the PIR read).
        pin : BCM pin — must be a hardware-PWM pin (12/13/18/19).
        """
        self._pi = pi
        self.pin = pin
        self._active = False

    def _tone(self, freq: int, duty: int = config.ULTRASONIC_DUTY):
        # hardware_PWM(gpio, frequency_hz, dutycycle_0_to_1_000_000)
        self._pi.hardware_PWM(self.pin, freq, duty)

    def _off(self):
        self._pi.hardware_PWM(self.pin, 0, 0)

    def sound_alarm(self, duration: float = config.BUZZER_DURATION):
        """Emit randomized ultrasonic tones across the configured band."""
        self._active = True
        step = config.ULTRASONIC_STEP_MS / 1000.0
        end = time.time() + duration
        try:
            while time.time() < end:
                freq = random.randint(config.ULTRASONIC_MIN_HZ,
                                      config.ULTRASONIC_MAX_HZ)
                self._tone(freq)
                time.sleep(step)
        finally:
            self._off()
            self._active = False

    def short_beep(self, freq: int = 25_000, ms: int = 200):
        """Single short tone for status feedback (ultrasonic by default)."""
        self._tone(freq)
        time.sleep(ms / 1000.0)
        self._off()

    def cleanup(self):
        if self._active:
            self._off()
            self._active = False
